"""Build an original English-language book for public Modu screenshots."""
from make_screenshot_book import build

CHAPTERS = [
    ('A Page Worth Staying With', [
        'Reading is an invitation to give something our full attention.',
        'On a quiet morning, a reader opens a book beside the window. There is no deadline, no list of facts to collect, and no prize for reaching the final page. A sentence catches her attention. She reads it again, more slowly this time, and notices a question she had passed over the night before. The room has not changed, but the page has.',
        'We often measure reading by how much ground we cover. Yet understanding does not always move at the speed of our eyes. A paragraph may need a pause. An unfamiliar word may deserve a search. An argument may become clear only when we put it into our own language. These small interruptions are part of reading, rather than obstacles to it.',
        'Try staying with one page for a little longer than usual. Ask what the writer is trying to explain. Look for the reasons behind a claim, and notice what has been left unsaid. If an example feels convincing, consider whether it would work in a different situation. A useful question makes a page larger without adding a single word.',
        'A bookmark can keep a place, but a note can keep a thought. Instead of copying everything that seems important, write down what surprised you and why. Perhaps a sentence connects two ideas you had kept apart. Perhaps an explanation leaves you unconvinced. Recording that response gives a future reader, who will be you again, somewhere to begin.',
        'There is also a place for reading without analysis. Follow the rhythm of a story, listen to a voice, or enjoy a description that brings an ordinary object into focus. Attention takes several forms. Sometimes it asks a precise question; sometimes it simply stays long enough to see what haste would miss.',
        'When you close the book, leave a little space before opening the next thing. Remember one image, one sentence, or one question. You need not settle it immediately. A good page can continue working after it disappears from view, quietly changing the way you notice the world.',
    ]),
    ('A Conversation Beside the Text', [
        'A reading companion is most useful when it helps us return to the book.',
        'An AI assistant can suggest an outline, explain an unfamiliar concept, or offer a different way to approach a difficult paragraph. Begin with a clear purpose. Do you want to remember a chapter, compare two claims, or understand the meaning of one word? The question shapes the answer, and a precise question is easier to check.',
        'Read the passage before asking about it. Your first impression matters, even when it is incomplete. Say which part is confusing, and explain what you think the writer means. This turns the conversation into a comparison between interpretations rather than an exercise in accepting the first confident response.',
        'A summary is a map, not the country. Return to the sentences it describes and look for the details it leaves behind. Does the writer qualify the claim? Is an example being mistaken for a general rule? An assistant can help locate these differences, but the text remains the place where they can be tested.',
        'For a question about a word, general knowledge may be enough. For a question about an unfamiliar name or a recent event, an outside source may be useful. Keep those tasks distinct. Ask for a source when verification matters, and pay attention to whether the source actually supports the explanation.',
        'A reusable prompt can make a good habit easier to remember. Ask for a central claim, its supporting reasons, and one question worth discussing. Adapt the prompt to the book you are reading. Poetry, history, and technical writing need different kinds of attention, even when they share the same screen.',
        'The aim is not to finish thinking sooner. It is to spend less time looking for a place to start and more time following an idea carefully. Let the assistant open a door, then step through it yourself. The most useful conversation leaves you with a clearer view of the page.',
    ]),
    ('Notes That Grow With You', [
        'A useful note preserves a relationship between a sentence and a thought.',
        'Highlight a passage because it matters to a question, not merely because it sounds memorable. Beside it, write a short explanation of the connection. What does it help you understand? What does it challenge? A note becomes easier to use when it records the reason for keeping the quotation.',
        'Leave room for disagreement. A clear argument can still depend on assumptions you do not share. Describe those assumptions before deciding whether to accept the conclusion. You may discover that the disagreement concerns a definition, an example, or the scope of a claim rather than the whole idea.',
        'Return to earlier notes after reading something new. Understanding changes, and a record of that change is valuable. A question that once seemed abstract may become practical. A confident answer may become uncertain. Add the new thought beside the old one instead of erasing the path you took.',
        'Organize notes around connections when possible. Two books may ask the same question in different ways. A story may illuminate a concept from an essay. A definition may help explain an experience outside the book. These links turn a collection of quotations into a resource you can think with.',
        'Keep the quotation separate from your own response. The quoted words should remain accurate; the response can be tentative, personal, and unfinished. A clear boundary makes it easier to cite the writer and easier to notice where your interpretation begins. Both parts matter, but they do different work.',
        'A note does not need to become an essay. A small diagram, a question, or a few plain sentences may be enough to preserve the connection. Write for the person who will return to the page later. Give that person a reason to care and a place to continue.',
        'As your collection grows, choose a few notes to revisit rather than trying to review everything. Follow one question through several entries. Notice where the evidence changed and where your attention moved. The purpose of keeping a record is not to make a perfect archive, but to make further thinking possible.',
    ]),
    ('The Shape of a Question', [
        'A question becomes useful when we can tell what kind of answer it needs.',
        'Mira once wrote only two words beside a difficult passage: not clear. The note preserved her frustration but little else. When she returned to it, she tried again. Was the unfamiliar term the problem? Had the writer skipped a step? Did the example support the conclusion? Each possibility pointed toward a different task.',
        'She chose one question and wrote it in full: why does the writer move from this particular case to a claim about everyone? Then she listed the conditions of the case and compared them with the reach of the claim. The passage was still difficult, but the difficulty now had edges. She could examine it without guessing where to begin.',
        'Some questions ask for facts, some for meanings, and some for judgments. A factual question needs evidence. A question about meaning needs context and careful use of language. A judgment needs a standard that can be discussed. These tasks often meet on the same page, but one kind of answer cannot quietly stand in for all the others.',
        'When two writers appear to disagree, check whether they are answering the same question. They may use one word in different senses, consider different circumstances, or address different audiences. This does not make disagreement disappear. It makes the disagreement precise enough to understand and, perhaps, to investigate.',
        'Good questions also leave room for an unexpected answer. If we ask only for confirmation, we may overlook information that would change our view. Try restating a position fairly before challenging it. Identify the evidence that could make you reconsider. A discussion becomes more useful when understanding matters more than winning.',
        'Not every question can be settled today. Some require another source, some a fuller explanation, and some an experience we have not yet had. Record what is known, what remains uncertain, and what might help next. An unanswered question with a clear next step is different from a question left in a fog.',
        'That evening, Mira answered one of her three questions. She did not consider the reading unfinished. The other two had become clearer than they were in the morning, and she knew what to look for. Sometimes the most honest result of careful reading is a better description of what we do not yet understand.',
    ]),
    ('A Small Library of Connections', [
        'Books can stand on their own, and they can become bridges to other books.',
        'The shelves divide subjects neatly, but ideas rarely respect every division. A story about a neighborhood may help us think about public space. An essay about memory may change the way we read an old journal. The connection is not a replacement for either book. It is a new question that becomes possible between them.',
        'Mira found the same image in a personal essay and a work of popular science. At first she wanted to treat the resemblance as agreement. Instead, she wrote down what each writer was using the image to explain. The shared language opened a door; the differences told her whether it led anywhere worth going.',
        'Keep the source and setting of a passage when making a connection. A sentence removed from its original question can appear stronger, simpler, or stranger than it really is. Record the book, the chapter, and your explanation of the link. Later, these details will help you return to the evidence rather than relying on a memorable phrase.',
        'You can organize a small reading project around one ordinary question. How do habits form? A story offers a lived situation, a study offers evidence to examine, and a journal offers personal observations. Each kind of material has a role. None should be made to carry a conclusion it was not designed to support.',
        'Connections do not require everything to agree. Mark the differences as carefully as the similarities. Which conditions have changed? Where is the evidence limited? Which claim reaches further than the others? A useful diagram shows not only the lines between ideas but also the places where a line would be misleading.',
        'Arranging a library and understanding it are different activities. Folders help us find material. Comparison and rereading help us use it. As a collection on one subject grows, write a short note about its purpose: what question brought these books together, and what has reading them helped you see so far?',
        'Over time, Mira remembered more than what a single writer had said. She began to notice how a question changed as it traveled through different kinds of text. Her shelves became less like a store of completed answers and more like a set of conversations she could reopen whenever she needed a fresh beginning.',
    ]),
    ('Returning to a Familiar Page', [
        'Rereading is not standing still, because the reader who returns has changed.',
        'On a first reading, we often follow the plot, the conclusion, or the novelty of an idea. On a second, attention may turn to structure and detail. A transition that once passed unnoticed can explain the whole argument. A quiet description may connect with an experience that had not happened when we first encountered it.',
        'Mira opened a bookmark she had left a year earlier. She remembered the excitement of the passage but no longer fully agreed with the note beside it. She added a new response without deleting the old one. The earlier note showed what had persuaded her then; the later one showed what she could now see differently.',
        'Begin a rereading with a question if that suits your purpose. Find the relevant chapter and read around the marked passage. Look for qualifications you may have missed and examples you may have remembered too simply. A small return to the surrounding text often gives more than another glance at an isolated quotation.',
        'Some books invite a complete return. Once the ending is familiar, we can notice how it is prepared: the order of information, the early hint, the change in rhythm. The destination is no longer the only reason to read. The way a book moves becomes part of its meaning and part of its pleasure.',
        'Write a brief record of the return. Why did you reopen the book? Which detail changed your understanding? What came from the text, and what came from your life outside it? The note does not need to prove that you have improved. It needs only to give an honest account of a change.',
        'The table by the window was the same table, but the book was no longer only the book Mira had first opened there. She closed it with one question still unresolved and decided to keep that question for another visit. Familiarity had not ended her curiosity. It had given curiosity a more definite direction.',
        'The Quiet Reader is an original six-chapter English book written for the Modu documentation. It contains no private material and does not reproduce an AI response from the application. Its text and EPUB are distributed with the project under GPL-3.0-or-later, for public reading demonstrations and exploration of the application.',
    ]),
]

if __name__ == '__main__':
    build(chapters=CHAPTERS, filename='modu-reading-demo-en.epub',
          title='The Quiet Reader', creator='Modu Documentation', language='en',
          identifier='urn:modu:documentation:reading-demo:en:1')
